#contacts-settings: "D:\\SAVCHUK\\SKILLBOX\\Spring\\contact-book\\src\\main\\resources\\contacts.txt"
spring:
 profiles:
  active: read
---
# загрузка контактов из базы контактов, загруженной в программу
spring:
 profiles: init
contacts-settings:
  file: D:\\SAVCHUK\\SKILLBOX\\Spring\\contact-book\\src\\main\\resources\\init-contacts.txt
---
# загрузка контактов из базы, сохраненной по результатам работы программы
spring:
 profiles: read
contacts-settings:
  file: D:\\SAVCHUK\\SKILLBOX\\Spring\\contact-book\\src\\main\\resources\\contacts.txt

