spring:
 profiles:
  active: init
---
# загрузка default контактов из сторонней базы по умолчанию
spring:
 profiles: init
contacts-settings:
 file-load: D:\\SAVCHUK\\SKILLBOX\\Spring\\contact-book\\src\\main\\resources\\default-contacts.txt
---
# загрузка контактов из базы, сохраненной по результатам работы программы
spring:
 profiles: read
contacts-settings:
 file-load-read: D:\\SAVCHUK\\SKILLBOX\\Spring\\contact-book\\src\\main\\resources\\contacts.txt
---
# запись контактов в базу
file-save: D:\\SAVCHUK\\SKILLBOX\\Spring\\contact-book\\src\\main\\resources\\contacts.txt