spring:
  profiles:
    active: read
---
spring:
  config:
    activate:
      on-profile: init
file-load: D:\\SAVCHUK\\SKILLBOX\\Spring\\contact-book\\src\\main\\resources\\default-contacts.txt

---
spring:
  config:
    activate:
      on-profile: read
file-load: D:\\SAVCHUK\\SKILLBOX\\Spring\\contact-book\\src\\main\\resources\\contacts.txt

---
file-save: D:\\SAVCHUK\\SKILLBOX\\Spring\\contact-book\\src\\main\\resources\\contacts.txt


#file-load: C:\\IdeaProjects\\contact-book\\src\\main\\resources\\default-contacts.txt
#file-load: C:\\IdeaProjects\\contact-book\\src\\main\\resources\\contacts.txt
#file-save: C:\\IdeaProjects\\contact-book\\src\\main\\resources\\contacts.txt